version: "3.7"
services:
  cloudflare-dns-tls:
    image: qmcgaw/cloudflare-dns-server
    container_name: cloudflare-dns-tls
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=0
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=off
      - BLOCK_IPS=
      - BLOCK_HOSTNAMES=
      - UNBLOCK=
      - PROVIDER=cloudflare,quad9
      - UPDATE_PERIOD=24h
    ports:
      - 53:53/udp
    network_mode: bridge
    restart: always
