version: "3.7"
services:
  cloudflare-dns-tls:
    build: .
    image: qmcgaw/cloudflare-dns-server
    container_name: cloudflare-dns-tls
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=1
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - BLOCK_IPS=
      - BLOCK_HOSTNAMES=
      - UNBLOCK=
      - PROVIDER=cloudflare,quad9
    ports:
      - 53:53/udp
    network_mode: bridge
    restart: always
